client_config_backend: settings
client_config:
  client_id : 238197358312-ovsgfscppm6tsko4k1ldjhpt141p39sr.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install